# Generated by Django 2.2.5 on 2019-09-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
