# Generated by Django 2.2.5 on 2019-09-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190905_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes'),
        ),
    ]
