# Generated by Django 2.2.5 on 2019-09-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos_clientes'),
        ),
    ]
